services:
  - type: web
    name: stock-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn stock_dashboard.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
